blank_issues_enabled: false
contact_links:
  - name: CCTVCraft 5 - Feature Requests
    url: https://github.com/northwesttrees-gaming/CCTVCraft-5/discussions/categories/suggestions
    about: Share ideas and feature requests here.
  - name: CCTVCraft 5 - Wiki
    url: https://github.com/northwesttrees-gaming/CCTVCraft-5/wiki
    about: Learn how the mod works on the official wiki.
